sudo: false

language: python

python: 3.8.1

install:
  - pip install coverage
  - pip install codecov

script:
  - coverage run sumTest.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
