sudo: false

language: python

python: 3.8.1

install:
  - pip install codecov
  - pip install coverage


script:
  - python sumTest.py


after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN