language: python

python: 3.8.1

install:
  - pip install coverage
  - pip install codecov

script:
  - coverage run sumTest.py

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - codecov

after_failure:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - codecov

addons:
  ssh_known_hosts: moon.scs.ryerson.ca
  
before_install:
  - openssl aes-256-cbc -K $encrypted_2e3610291f91_key -iv $encrypted_2e3610291f91_iv
  - in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet 
          ${TRAVIS_BUILD_DIR}/cps847assignment2
          ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/${DEPLOY_USER}
  on:
    branch: master
